import { NextRequest, NextResponse } from "next/server";
import { supabase } from "@/lib/supabase";

const PRICING = {
  basic: 75000,
  premium: 99000,
};

export type OrderStatus =
  | "pending_payment"
  | "awaiting_confirmation"
  | "paid"
  | "in_production"
  | "published"
  | "cancelled";

export interface Order {
  id: number;
  order_id: string;
  template: string;
  package: "basic" | "premium";
  price: number;
  customer_name: string;
  customer_phone: string;
  customer_email: string | null;
  wedding_data: any;
  status: OrderStatus;
  admin_notes: string | null;
  created_at: string;
  updated_at: string;
}

export interface WeddingData {
  groomFullName: string;
  brideFullName: string;
  akadDate: string;
  akadStartTime: string;
  akadEndTime: string;
  akadAddress: string;
  hasResepsi: boolean;
  resepsiDate: string;
  resepsiStartTime: string;
  resepsiEndTime: string;
  resepsiAddress: string;
}

export async function POST(req: NextRequest) {
  try {
    if (!supabase) {
      return NextResponse.json(
        { error: "Database belum dikonfigurasi" },
        { status: 503 }
      );
    }

    const body = await req.json();

    const {
      template,
      package: pkg,
      customer_name,
      customer_phone,
      customer_email,
      wedding_data,
    } = body;

    if (!template || !pkg || !customer_name || !customer_phone) {
      return NextResponse.json(
        { error: "Field wajib: template, package, customer_name, customer_phone" },
        { status: 400 }
      );
    }

    if (pkg !== "basic" && pkg !== "premium") {
      return NextResponse.json(
        { error: "Package harus 'basic' atau 'premium'" },
        { status: 400 }
      );
    }

    const price = PRICING[pkg as "basic" | "premium"];

    // Insert — order_id auto-generated by Supabase trigger (NAUKA-0001, NAUKA-0002, ...)
    const { data, error } = await supabase
      .from("orders")
      .insert({
        template,
        package: pkg,
        price,
        customer_name: customer_name.trim(),
        customer_phone: customer_phone.trim(),
        customer_email: customer_email?.trim() || null,
        wedding_data: wedding_data || null,
        status: "pending_payment",
      })
      .select()
      .single();

    if (error) {
      console.error("[api/orders] insert error:", error);
      return NextResponse.json(
        { error: "Gagal membuat pesanan: " + error.message },
        { status: 500 }
      );
    }

    return NextResponse.json({
      data: data as Order,
      message: "Pesanan berhasil dibuat",
    });
  } catch (err: any) {
    console.error("[api/orders] unexpected:", err);
    return NextResponse.json(
      { error: "Terjadi kesalahan server" },
      { status: 500 }
    );
  }
}

export async function GET(req: NextRequest) {
  try {
    if (!supabase) {
      return NextResponse.json(
        { error: "Database belum dikonfigurasi" },
        { status: 503 }
      );
    }

    const { searchParams } = new URL(req.url);
    const status = searchParams.get("status");
    const limit = parseInt(searchParams.get("limit") || "50");
    const page = parseInt(searchParams.get("page") || "1");
    const offset = (page - 1) * limit;

    let query = supabase
      .from("orders")
      .select("*", { count: "exact" })
      .order("created_at", { ascending: false })
      .range(offset, offset + limit - 1);

    const VALID_STATUSES: OrderStatus[] = [
      "pending_payment",
      "awaiting_confirmation",
      "paid",
      "in_production",
      "published",
      "cancelled",
    ];

    if (status && VALID_STATUSES.includes(status as OrderStatus)) {
      query = query.eq("status", status);
    }

    const { data, error, count } = await query;

    if (error) {
      return NextResponse.json({ error: error.message }, { status: 500 });
    }

    return NextResponse.json({
      data: data as Order[],
      total: count,
      page,
      limit,
    });
  } catch (err: any) {
    return NextResponse.json(
      { error: "Terjadi kesalahan server" },
      { status: 500 }
    );
  }
      }
